[battery]
disabled = true

[directory]
read_only = "RO"

# git_status is painfully slow in large repos
[git_status]
disabled = true

[golang]
symbol = "GOLANG "

[hostname]
ssh_only = false
format = "@[$hostname]($style):"

[nix_shell]
symbol = "NIX-SHELL "

[nodejs]
symbol = "NODEJS "

[package]
symbol = ""

[python]
symbol = "PYTHON "

[ruby]
symbol = "RUBY "

[rust]
symbol = "RUST "

[status]
disabled = false
symbol = "E"

[time]
disabled = false
format = "[$time]($style) "

[username]
format = "[$user]($style)"
show_always = true
