[directory]
read_only = "RO"

# git_status is painfully slow in large repos
[git_status]
disabled = true

[hostname]
ssh_only = false
format = "@[$hostname]($style):"

[nix_shell]
symbol = "NIX-SHELL"

[package]
symbol = ""

[ruby]
symbol = "RUBY "

[rust]
symbol = "RUST "

[status]
disabled = false
symbol = "E"

[time]
disabled = false

[username]
format = "[$user]($style)"
